# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  lane :beta do
    gradle(task: "clean assembleRelease")
    gradle(
        task: "assemble",
        build_type: "Release",
        print_command: false,
        properties: {
            "android.injected.signing.store.file" => ENV['ANDROID_LIS_PARTNER_KEYSTORE_PATH'],
            "android.injected.signing.store.password" => ENV['ANDROID_LIS_PARTNER_KEYSTORE_PASSWORD'],
            "android.injected.signing.key.alias" => "Inivivo Partner",
            "android.injected.signing.key.password" => ENV['ANDROID_LIS_PARTNER_KEYSTORE_PASSWORD'],
        }
    )
    Dir.chdir ".." do
        zealot(
            endpoint: 'https://log4test.pmr.vn',
            token: '320bacf980e20e7b058be2d77154dc53',
            channel_key: '936a41e85a77900f1903bc6f48ca932f',
            file: Dir.pwd + '/../android/app/build/outputs/apk/release/app-release.apk',
            changelog: ''
        )
    end

  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    gradle(
        task: "bundle",
        build_type: "Release",
        print_command: false,
        properties: {
            "android.injected.signing.store.file" => ENV['ANDROID_LIS_PARTNER_KEYSTORE_PATH'],
            "android.injected.signing.store.password" => ENV['ANDROID_LIS_PARTNER_KEYSTORE_PASSWORD'],
            "android.injected.signing.key.alias" => "Inivivo Partner",
            "android.injected.signing.key.password" => ENV['ANDROID_LIS_PARTNER_KEYSTORE_PASSWORD'],
        }
    )
    upload_to_play_store(skip_upload_apk: true)
  end
end
