# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"

  lane :beta do
    gradle(task: "clean assembleRelease")

    gradle(
        task: "assemble",
        build_type: "Release",
        print_command: false,
        properties: {
            "android.injected.signing.store.file" => "keystore.jks",
            "android.injected.signing.store.password" => "",
            "android.injected.signing.key.alias" => "alias_key",
            "android.injected.signing.key.password" => "",
        }
    )

  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    gradle(
        task: "bundle",
        build_type: "Release",
        print_command: false,
        properties: {
            "android.injected.signing.store.file" => "keystore.jks",
            "android.injected.signing.store.password" => "",
            "android.injected.signing.key.alias" => "alias_key",
            "android.injected.signing.key.password" => "",
        }
    )
    upload_to_play_store(skip_upload_apk: true)
  end
end
